# Generated by Django 4.2 on 2024-07-10 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0004_alter_lesson_course'),
        ('users', '0005_remove_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_payment', models.PositiveSmallIntegerField(verbose_name='Дата оплаты')),
                ('payment_amount', models.PositiveBigIntegerField(verbose_name='Сумма оплаты')),
                ('payment_method', models.CharField(choices=[('cash', 'наличные'), ('transfer', 'перевод')], default='transfer', max_length=80, verbose_name='способ оплаты')),
                ('course_paid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='material.course', verbose_name='курс')),
                ('lesson_paid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='material.lesson', verbose_name='урок')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
