# Generated by Django 4.2 on 2024-07-10 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_payments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payments',
            options={'ordering': ('-date_payment',), 'verbose_name': 'Оплата', 'verbose_name_plural': 'Оплаты'},
        ),
    ]
