# Generated by Django 4.2 on 2024-07-10 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_payments_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payments',
            old_name='course_paid',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='payments',
            old_name='lesson_paid',
            new_name='lesson',
        ),
    ]
