# Generated by Django 4.2 on 2024-07-23 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
