# Generated by Django 4.2 on 2024-07-10 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0004_alter_lesson_course'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ('title',), 'verbose_name': 'Урок', 'verbose_name_plural': 'Уроки'},
        ),
    ]
